---
- name: Test Ansible Connectivity
  hosts: all
  become: yes
  gather_facts: false

  tasks:

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install Docker if not present
      ansible.builtin.package:
        name: docker.io
        state: present
    
